application: findmechicken
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- appstats: on

handlers:
- url: /cron/.*
  script: cron.app
  login: admin

- url: /.*
  script: main.app